// app/layout.server.tsx
import { Metadata } from 'next';
import LayoutClient from './layout.client'; // Import the client-side layout

export const metadata: Metadata = {
  title: 'Foody App',
  description: 'Generated by Rsk',
  // You can add other global meta tags like Open Graph, etc.
};

export default function LayoutServer({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Add any global <head> content like fonts, styles, etc. */}
      </head>
      <body>
        {/* The client-side layout is wrapped here */}
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
