import type { Metadata } from "next";
import { Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Image from 'next/image';
import fruitLogo from '../assets/fruit-mosaique.jpg';

function FruitIcon() {
  return (
    <div className='' data-twe-ripple-init
    data-twe-ripple-color="light">
      <Image
        src={fruitLogo}
        width={75}
        className='rounded-3xl max-w-xs transition duration-300 ease-in-out hover:scale-110 cursor-pointer'
        alt="Picture of the App icon"
      />
    </div>
  );
}

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
const montserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

const montserratMono = Geist_Mono({
  variable: "--font-montserrat-mono",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Foody App",
  description: "Generated by rsk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable} ${montserratMono.variable} antialiased flex flex-row-reverse h-screen bg-gradient-to-bl from-orange-300 to-rose-600`}
      >
        <div className='flex flex-grow flex-start justify-end p-5'>
          <FruitIcon />
        </div>
        {children}
      </body>
    </html>
  );
}
